name: Checkov
on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: makandra/github-actions/checkov-terraform@main
        with:
          path: modules/
