name: Checkov
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          framework: terraform
          # CKV_AWS_252 is optional and not required
          # CKV2_AWS_10 is optional and not required
          skip_check: CKV_AWS_252,CKV2_AWS_10
